### ISSUE TITLE
Out of source tree builds broke after commit 9649787

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icecream#127]
After commit 964978733462511832d08ec9670a93b1867a018f out of source tree builds do not work. In source builds still work. 

```
CXX      remote.o
../../icecream/client/remote.cpp:54:27: fatal error: services/util.h: No such file or directory
 #include "services/util.h"
                           ^
compilation terminated.
make[2]: *** [remote.o] Error 1
```

This commit added the not found include.

**Comment by llunak** [comment]
This must have been fixed ages ago.
